### ISSUE TITLE
[BUG] Video Not Found error

### ISSUE THREAD

**Issue by stingersplash** [thecoder75/liveme-pro-tools#107]
I have been noticing lately that 2 things seem to happen
1- when playing replay, the screen stays black and video never plays, almost life it is searching for replay.
2-when I try to play a video (happening a lot lately) a grey screen appears and says
Video not found!
This live stream ended 1week ago.
The replay might still being generated or was deleted.
Try again later, maybe?
I use different methods to play m3u8's when this happens, so that's great, but just wanted to let you know what I have been noticing lately.

**Comment by thecoder75** [comment]
This is due to the recent updates LiveMe has performed.  It seems now they are flagging or taking videos down causing this issue.  

I've researched the results of the API calls and they are actually not even sending any of the required data, instead just sending back a video info record with less data than normal.

**Comment by thecoder75** [comment]
See #108 as I've updated the code base to fix the issues.
