### ISSUE TITLE
Feature Requests for 2019

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-pro-tools#30]
Features requested for moving forward for developers to work on.  Add your request as a comment and we'll look into it.

- [x] ~~Change location for downloaded replays (Was there a long time ago but is missing now I think)~~ (Still there)
- [ ] ~~Video Player Rotation~~
- [x] Integrate LAMD function into main app? (Config settings are integrated only!)
- [x] Bookmark cleanup function (flag or remove accounts that haven't been viewed in x days, etc...)
- [ ] ~~Bookmark Configuration page (to configure scanning/ignoring for each bookmark individually, create categories and assign/desaign bookmarks to them)~~
- [ ] ~~Introduce Machine Learning (???)~~
- [x] Dedicated home screen window, update results open in new window
- [ ] Ability to cancel active downloads
- [ ] Ability to view/show additional account profile info (like signatures, praises, etc...)
- [x] Ability to download the chat history log as a text file
- [x] Show the number of new fans/followers on the home page during new scan
- [x] Button to copy a link to the user's profile page (https://www.liveme.com/us/u/[user_long_id]
- [ ] ~~Cache everything~~

**Comment by Xqqz** [comment]
Highlight BANNED ACCOUNTS with a RED BACKGROUND in Bookmarks after a SCAN

When the Bookmarks is scanned,  LMPT already detects that an account is banned, ( right ? )
 because when you click on a BANNED ACCOUNT after a scan, you get a screen similar to whats  shown below.
So when LMPT detects " No replays! There is no publicly listed replays available" , it can return the result a RED BACKGROUND in the scanned result for those accounts, similar to how it returns a GREEN background for NEW REPLAYS, similar to how it returns a YELLOW BACKGROUND when an account adds NEW FOLLOWINGS or got NEW FANS

If i see a bunch of RED BACKGROUNDS  ( highlighted-banned accounts ) i can scroll down and UNFOLLOW them easily, ( cleaning up bookmarks ) 

![banned](https://user-images.githubusercontent.com/38635388/50513060-67bd2580-0a63-11e9-9813-df14f514ab80.jpg)


What says the community ?

**Comment by Xqqz** [comment]
Integrate LAMD
So we can schedule auto-scan and auto-download of  selected broadcasters Live

**Comment by Grindteeth** [comment]
Some kind of clean up functionality, i.e. "remove all accounts not viewed in x months". If you decide to implement this, I'd appreciate if we get a pop up lining up all accounts (with short ID) that will be removed after the action since I will manually remove these from the LM client. Optionally, this pop up could allow us to select which ones to remove (or the ability to mark an account as "save forever" so it won't even show up in this list).

**Comment by thecoder75** [comment]
> 
> 
> Highlight BANNED ACCOUNTS with a RED BACKGROUND in Bookmarks after a SCAN
> 
> When the Bookmarks is scanned, LMPT already detects that an account is banned, ( right ? )
> because when you click on a BANNED ACCOUNT after a scan, you get a screen similar to whats shown below.
> So when LMPT detects " No replays! There is no publicly listed replays available" , it can return the result a RED BACKGROUND in the scanned result for those accounts, similar to how it returns a GREEN background for NEW REPLAYS, similar to how it returns a YELLOW BACKGROUND when an account adds NEW FOLLOWINGS or got NEW FANS
> 
> If i see a bunch of RED BACKGROUNDS ( highlighted-banned accounts ) i can scroll down and UNFOLLOW them easily, ( cleaning up bookmarks )
> 
> ![banned](https://user-images.githubusercontent.com/38635388/50513060-67bd2580-0a63-11e9-9813-df14f514ab80.jpg)
> 
> What says the community ?

Cannot show the account as being banned as they may have just deleted or removed all of the replays or set them to be hidden.  I don't want people getting confused because of the app interpreting things incorrectly.

**Comment by Xqqz** [comment]
This feature from your list
""" Bookmark cleanup function (flag or remove accounts that haven't been viewed in x days, etc...)""

I believe should just FLAG the account, don't want LMPT automatically REMOVING the users from the Bookmark until we can manually check to see if the account  is banned from LiveMe or they just have not  broadcast in a long time.. 
I have seen broadcasters return to Liveme and go Live after being missing for 5 months... just my .02 cents

**Comment by RandomUserDave** [comment]
Requesting persistent replay index.  Links to replays are lost (if deleted) when the user's index is refreshed.  I'm hoping there's a way to keep the list of replays locally, adding new ones when refreshed but not replacing the entire list.  Great tool, btw.  Thanks for all your work on this.

**Comment by monstergarden** [comment]
@RandomUserDave Yes this was actually planned with the new dotnet core version.
We plan to store every request to the liveme backend in a local DB file (cache).

**Comment by holamogan41** [comment]
Is it possible to change tips settings? I want to take 3 seconds forward or backward.

**Comment by thecoder75** [comment]
Closing this for now, will open individual issue tickets for each feature as we plan to add them.
