### ISSUE TITLE
Replay list suggestion

### ISSUE THREAD

**Issue by amr18379** [thecoder75/liveme-pro-tools#61]
Hello,

I'm just  user  for this great tool and i was following up since the old versions of live.me tool , so I would like to  suggest to add some features were added in the old versions such as LiveMeTools 6.3.3   and hopefully it will be implement, for the more advanced project "liveme pro tools" ,the suggested features are:-

1- Add import function  for all replays list per each broadcaster .
2- Add liveomg module in the menu list and option to add the broadcaster as favorite.

Thanks in advance

**Comment by thecoder75** [comment]
Regarding number one - Why do you want to import a list of replays?  If its for downloading, you can use jDownloader 2 to handle that instead when dealing with large lists of replays.  Otherwise I see no point in importing a list of replays into the app.

Regarding number two - [LiveMeOMG](https://github.com/thecoder75/livemeomg) will **never** be added to LiveMe Pro Tools.  The whole purpose of this project is to create a tool designed to help in searching, analyzing and downloading of replays only.  It's **not** to recreate the LiveMe app or web site in any form, which is what [LiveMeOMG](https://github.com/thecoder75/livemeomg) did.

Sorry but neither of your requests will be fulfilled.
