### ISSUE TITLE
Transform Error

### ISSUE THREAD

**Issue by JustALostCoder** [thecoder75/liveme-pro-tools#75]
Giving me following error when trying to log in.

TransformError:SyntaxError: Unexpected token < in JSON at position 0

**Comment by thecoder75** [comment]
This error is a result of either your login account being banned or your IP address being blocked by LiveMe.  I've added a catch now for the error that will throw a message indicating this now instead.

**Comment by JustALostCoder** [comment]
Cannot login since then. Following error occurs:

![eror liveme](https://user-images.githubusercontent.com/38503931/53300043-07304600-3864-11e9-9354-4d39ce60c648.jpg)

**Comment by thecoder75** [comment]
Either your account is no longer valid on LiveMe or LiveMe has banned your IP address.

No one else is having problems logging in including myself.  I'm afraid there is no fixing your issue as it is not related to LMPT or the API module.

**Comment by JustALostCoder** [comment]
Account is working fine. I can connect on livme app on phone with the same internet.

**Comment by thecoder75** [comment]
If you registered with LiveMe using Google or Facebook with that email instead of using just an email account, then it will not work with LMPT.  There is no way around it and nothing can be done as you will have to create a whole new login with LiveMe using the email registration method and use that instead.

This issue is now closed and will no longer receive responses from me as this issue is **NOT** related to LMPT in any way, shape or form.
