### ISSUE TITLE
download problem with 1.328.20190222 linux appimage

### ISSUE THREAD

**Issue by TuxNuX** [thecoder75/liveme-pro-tools#77]
have this problem when download
![screenshot_20190226_054706](https://user-images.githubusercontent.com/17123357/53410944-9012c300-39c5-11e9-9f12-0077fd8aa206.png)
![screenshot_20190226_054638](https://user-images.githubusercontent.com/17123357/53410953-95700d80-39c5-11e9-9f36-549c8fe6b1e6.png)

despite the crash and error message it is enqueue but never starts the download
when i manually download with m3u8 link do not have any problem

**Comment by thecoder75** [comment]
It is a known issue and actually is being caused by LiveMe servers screwing with replay chunk names that caused this.  I've already posted a fix to the repo for this issue as I've experienced it myself on 5 out of 1000 replays so far.  Expect a new build to be released either today or tomorrow which will contain the fix.  

Until then, switching to FFMPEG downloader from the built-in chunk downloader does allow downloads to work even with this issue.
