### ISSUE TITLE
build rpm package

### ISSUE THREAD

**Issue by TuxNuX** [thecoder75/liveme-pro-tools#79]
I would like to do spec file for build rpm package, but I do not know how to compile with electron js, is it possible to do a mini tutorial for compile with the buildrequires and the requires

**Comment by monstergarden** [comment]
`npm run release `

**Comment by thecoder75** [comment]
@monstergarden The build script was just updated to support RPM building this morning.
@TuxNuX Releases will now include an RPM package file.

**Comment by TuxNuX** [comment]
> @monstergarden The build script was just updated to support RPM building this morning.
> @TuxNuX Releases will now include an RPM package file.

thank for rpm package, but the shortcut  (.desktop) is missing
I would like to know how to use language fr.pak?

**Comment by thecoder75** [comment]
I'll look into the missing .desktop shortcut file.

Not sure how to use the fr.pak myself as I believe it to be a language pack and the app is only written in english at this time.

**Comment by mustang-sally** [comment]
@TuxNuX 

>thank for rpm package, but the shortcut (.desktop) is missing

I've just built the RPM package myself and there is a `.desktop` file:

```
$ rpm -qpl LiveMe_Pro_Tools-1.335.20190416-linux-x86_64.rpm | grep desktop
/usr/share/applications/liveme-pro-tools.desktop
```

And here are the contents:

```desktop
[Desktop Entry]
Name=LiveMe Pro Tools
Comment=Browse, search and manage accounts, replays and more without the need of an actual account on Live.me.
Exec="/opt/LiveMe Pro Tools/liveme-pro-tools" %U
Terminal=false
Type=Application
Icon=liveme-pro-tools
StartupWMClass=LiveMe Pro Tools
Encoding=UTF-8
Categories=Network;
```

I think you're misunderstanding how this works. The `.desktop` file is built by `electron-builder`, based on the contents of `package.json`, that's why you can't find a desktop file *per se* in this repository.

>I would like to know how to use language fr.pak?

The language packs are a part of the Chromium browser, so even if you could use any language pack it offers, it would only change the language of Chromium itself (e.g. debugging tools), having no effect on LiveMe Pro Tools.
