### ISSUE TITLE
Sort followers / fans

### ISSUE THREAD

**Issue by camoulin** [thecoder75/liveme-pro-tools#86]
I'm missing the possibility to sort the list of Followers and Fans by replays, fans and followings count. Is it something foreseeable in a near future ?

**Comment by thecoder75** [comment]
Due to most users keeping the Followers and Fans lists in dynamic loading mode, a feature like this would actually break and cause more problems then its worth.  Plus the fact that every account listed has to be queried to get counts and info, I don't see this being a viable option.

So unfortunately I will not be adding this feature, nor will I approve any Pull Requests adding this feature as it can induce more bugs or cause usage issues.
