### ISSUE TITLE
two small issues with New video player on Mac

### ISSUE THREAD

**Issue by stingersplash** [thecoder75/liveme-pro-tools#88]
The New video player works great, but it has two small issues on Mac.
1. Fullscreen doesn't work properly. When I click the bottom right corner of the player it should go into fullscreen, but instead it just hides the top bar of the player (top right corner where you exit out of video/view user options) and when I click it again, it reappears. Only way to use fullscreen is by adjusting the size of the player manually with the mouse. Also, the size of player I adjusted saves, so I don't have to keep adjusting it everytime I play a different video, which is great.
2. Rotation of video is a great addition, but when I adjust player size manually to my liking, and I rotate video, size of player resets to original small size, so I have to keep adjusting it back everytime I use the rotation feature.
These are just minor issues and everything else seems to work perfect. Thank you

**Comment by mustang-sally** [comment]
Hello, I'm the author of the new player.

Sorry to hear you're having issues with it. And to be honest, I didn't test this new player on a Mac machine at all, simply because I don't own one. I could investigate your first issue, but I'm not sure what it could be, since entering and leaving full screen mode works just fine on both Windows and Linux, based on my tests. Does double-clicking the video enter/leave full screen mode?

About the second issue, auto-resizing the player window to match the video's dimension was actually meant to be a feature, but I can see how annoying it can be. Anyway, I'll add a new option to disable this feature completely (and probably enable it by default) when I have some free time.

**Comment by stingersplash** [comment]
Does double-clicking the video enter/leave full screen mode?
No, doesn't seem to work. All it does is hide the exit out of video/view user options and when i click it again, it reappears. Nothing really major, just an inconvenience. I'm use to it already.
(About the second issue, auto-resizing the player window to match the video's dimension was actually meant to be a feature, but I can see how annoying it can be)
its not really that bad, but if you can add that option, that would be great. This video player is well worth it compared to an external player. Thanks again

**Comment by mustang-sally** [comment]
Thanks a lot for the feedback!

I was able to fix the fullscreen issue on macOS, and I've added some options to customize the new player as well. I'm also planning to fix some other (unrelated) small bugs I found. Since most of those fixes are on my home PC and I'm not at home atm, it will take some time until I'm able to send a pull request. In the meantime, if you have some other suggestions or bugs you've found, please feel free to post them.
