### ISSUE TITLE
Profile of some users say account terminated, but continues to produce new replays days later...

### ISSUE THREAD

**Issue by stingersplash** [thecoder75/liveme-pro-tools#93]
Issue is on mac version, I don't know if this happens on windows,etc

Hi, so I have been noticing lately(about 3 or 4 times) that sometimes a user's profile will say
"Uhh oh! This users account has been terminated by the looks of things!"
with 0 replays, and then say 24-48hours later, the users account is back with all past replays and also new replays. Seems like a small glitch. Just thought I would let you know so someone will not accidentally delete an account thinking it was terminated.

**Comment by Xqqz** [comment]
@stingersplash 
When a see an account on LMPT as "banned", i usually verify by going on LiveMe app and checking.

So, when an account "returns", its because Liveme has actually REINSTATE that account.

I ALWAYS verify if an account is really DELETED/BANNED by LiveMe, or if it was just "Suspended", if an account is NOT REINSTATED after 48 hours, then its a PERMANENT BANNED

It takes a lil bit of work on my part, but I always check "banned" accounts 3 days after, before i remove them from my Bookmarks.

**Comment by thecoder75** [comment]
This has been resolved - actually caused by replays being set to hidden or private and LiveMe servers not able to return a list of them since the account being used is not a friend of the broadcaster.
